server:
  port: 8087

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/notification_service_db

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'


  mail:
    host: smtp.gmail.com
    port: 587
    username: ######@gmail.com
    password: ##############
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  application:
    name: notification-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true