
server:
  port: 8081
  servlet:
    context-path: /auth


spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/auth_service_db
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework: INFO

jwt:
  signerKey: "Q1V/fLdExbIjkVheKTzzFWgrGAv7HVoWl3ZTbzR1E8nE2C2Ah/XWwVOH0d6sS3W/VbQ7tf61w6K2/6MWd6ecgA=="
  valid-duration: 3600
  refreshable-duration: 36000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true