server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/api/patients/**

        - id: staff-service
          uri: lb://staff-service
          predicates:
            - Path=/api/staffs/**

        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/api/appointments/**

        - id: prescription-service
          uri: lb://prescription-service
          predicates:
            - Path=/api/prescriptions/**

        - id: medicine-service
          uri: lb://medicine-service
          predicates:
            - Path=/api/medicines/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**

        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/api/reports/**

        - id: billing-service
          uri: lb://billing-service
          predicates:
            - Path=/api/billings/**


      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
